import Head from 'next/head';
import AllocationForm from '../components/allocation_form';
import AllocationResult from '../components/allocation_result';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-full w-full'>
        <div className='flex flex-row h-full'>
          <div className='basis-1/2 h-full'>
            <label className='my-title'>Inputs</label>
            <AllocationForm />
          </div>
          <div className='basis-1/2 h-full'>
            <label className='my-title'>Results</label>
            <AllocationResult />
          </div>
        </div>
      </main>
    </>
  );
}
