---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger-deployment
  namespace: default
  labels:
    app: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
      - name: debugger
        image: boyw165/debugger-zsh:latest
        # Keep the container running
        command: [ "/bin/zsh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi