---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:15.1
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-vol
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: database-pv-claim
