apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
