apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: api-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
